export function openApiDocument(version: string): Record<string, unknown> {
  const id = { type: "string", format: "uuid" };
  const location = { type: "object", required: ["id", "name", "latitude", "longitude", "timezone", "sortOrder", "analysisEnabled", "syncVersion"], properties: { id, name: { type: "string" }, latitude: { type: "number" }, longitude: { type: "number" }, timezone: { type: "string" }, alias: { type: ["string", "null"] }, countryCode: { type: ["string", "null"] }, admin1: { type: ["string", "null"] }, admin2: { type: ["string", "null"] }, sortOrder: { type: "integer" }, analysisEnabled: { type: "boolean" }, createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" }, deletedAt: { type: ["string", "null"], format: "date-time" }, syncVersion: { type: "integer" }, fallbackProvider: { type: "string" }, rawRetentionDays: { type: "integer" } } };
  const secure = [{ bearerAuth: [] }];
  const response = (schema: Record<string, unknown>) => ({ "200": { description: "OK", content: { "application/json": { schema } } }, "401": { description: "Authentication required" } });
  return { openapi: "3.0.3", info: { title: "MeteoHub Server API", version, description: "Single-user self-hosted weather analysis hub. All timestamps are ISO 8601 UTC unless a field explicitly says it is a location-local date." }, servers: [{ url: "/" }], paths: {
    "/api/v1/health": { get: { operationId: "health", responses: response({ type: "object" }) } },
    "/api/v1/version": { get: { operationId: "version", responses: response({ type: "object" }) } },
    "/api/v1/pairing-codes": { post: { operationId: "createPairingCode", responses: response({ type: "object", properties: { code: { type: "string" }, expiresAt: { type: "string", format: "date-time" } } }) } },
    "/api/v1/pair": { post: { operationId: "pairDevice", requestBody: { required: true, content: { "application/json": { schema: { type: "object", required: ["code", "deviceName"], properties: { code: { type: "string" }, deviceName: { type: "string" } } } } } }, responses: response({ type: "object" }) } },
    "/api/v1/devices": { get: { security: secure, operationId: "listDevices", responses: response({ type: "array" }) } },
    "/api/v1/devices/{id}": { patch: { security: secure, operationId: "renameDevice", parameters: [{ name: "id", in: "path", required: true, schema: id }], responses: response({ type: "object" }) }, delete: { security: secure, operationId: "revokeDevice", parameters: [{ name: "id", in: "path", required: true, schema: id }], responses: response({ type: "object" }) } },
    "/api/v1/locations": { get: { security: secure, operationId: "listLocations", responses: response({ type: "array", items: location }) }, post: { security: secure, operationId: "createLocation", responses: response(location) } },
    "/api/v1/locations/candidates": { get: { security: secure, operationId: "locationCandidates", parameters: [{ name: "latitude", in: "query", required: true, schema: { type: "number", minimum: -90, maximum: 90 } }, { name: "longitude", in: "query", required: true, schema: { type: "number", minimum: -180, maximum: 180 } }, { name: "timezone", in: "query", schema: { type: "string" } }, { name: "countryCode", in: "query", schema: { type: "string" } }], responses: response({ type: "array", items: { type: "object", required: ["location", "distanceKm", "match"], properties: { location, distanceKm: { type: "number" }, match: { type: "number" } } } }) } },
    "/api/v1/locations/{id}": { patch: { security: secure, operationId: "updateLocation", parameters: [{ name: "id", in: "path", required: true, schema: id }], responses: response(location) }, delete: { security: secure, operationId: "deleteLocation", parameters: [{ name: "id", in: "path", required: true, schema: id }], responses: response(location) } },
    "/api/v1/locations/reorder": { post: { security: secure, operationId: "reorderLocations", responses: response({ type: "array", items: location }) } },
    "/api/v1/locations/sync": { get: { security: secure, operationId: "syncLocations", parameters: [{ name: "since", in: "query", schema: { type: "integer", default: 0 } }], responses: response({ type: "object" }) } },
    "/api/v1/locations/{id}/forecast": { get: { security: secure, operationId: "getForecast", parameters: [{ name: "id", in: "path", required: true, schema: id }], responses: response({ type: "object" }) } },
    "/api/v1/locations/{id}/analysis": { get: { security: secure, operationId: "getAnalysis", parameters: [{ name: "id", in: "path", required: true, schema: id }], responses: response({ type: "object" }) } },
    "/api/v1/locations/{id}/evolution": { get: { security: secure, operationId: "getEvolution", parameters: [{ name: "id", in: "path", required: true, schema: id }, { name: "variable", in: "query", required: true, schema: { type: "string" } }], responses: response({ type: "array" }) } },
    "/api/v1/locations/{id}/performance": { get: { security: secure, operationId: "getPerformance", parameters: [{ name: "id", in: "path", required: true, schema: id }], responses: response({ type: "object" }) } },
    "/api/v1/sources": { get: { security: secure, operationId: "listSources", responses: response({ type: "object" }) } },
    "/api/v1/settings": { get: { security: secure, operationId: "getSettings", responses: response({ type: "object" }) }, patch: { security: secure, operationId: "updateSettings", responses: response({ type: "object" }) } },
  }, components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "device-token" } } } };
}
