import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { MODEL_REGISTRY } from "../domain/models.js";
import { requireAuth, type AuthService } from "../auth/auth.js";
import type { AppConfig } from "../config/config.js";
import type { Store } from "../storage/store.js";
import { openApiDocument } from "./openapi.js";

const idParam = z.object({ id: z.string().uuid() });
const locationInput = z.object({ name: z.string().trim().min(1).max(120), latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), timezone: z.string().min(1).max(80), countryCode: z.string().length(2).toUpperCase().nullable().optional(), admin1: z.string().max(120).nullable().optional(), admin2: z.string().max(120).nullable().optional(), alias: z.string().max(120).nullable().optional(), sortOrder: z.number().int().min(-100000).max(100000).optional(), analysisEnabled: z.boolean().optional(), fallbackProvider: z.string().max(80).optional(), rawRetentionDays: z.number().int().min(30).max(3650).optional() });
const patchLocation = locationInput.partial().extend({ expectedVersion: z.number().int().min(0).optional() });
const reorderInput = z.object({ ids: z.array(z.string().uuid()).min(1).max(100) });
const syncQuery = z.object({ since: z.coerce.number().int().min(0).default(0), limit: z.coerce.number().int().min(1).max(500).default(100) });
const evolutionQuery = z.object({ variable: z.string().min(1).max(80), validAt: z.string().datetime().optional() });
const settingsInput = z.object({ calibrationEnabled: z.boolean().optional(), ingestionEnabled: z.boolean().optional(), rawRetentionDays: z.number().int().min(30).max(3650).optional(), serverName: z.string().min(1).max(80).optional() });

export interface RouteOptions { store: Store; auth: AuthService; config: AppConfig; }

export async function registerRoutes(app: FastifyInstance, options: RouteOptions): Promise<void> {
  const { store, auth, config } = options;
  const withAuth = async (request: FastifyRequest, reply: FastifyReply): Promise<boolean> => requireAuth(request, reply, auth);
  app.get("/api/v1/health", async () => ({ status: "ok", service: "meteohub-server", timestamp: new Date().toISOString(), database: config.DATABASE_URL ? "configured" : "memory" }));
  app.get("/api/v1/version", async () => ({ version: config.APP_VERSION, apiVersion: "v1", node: process.version }));
  app.get("/api/v1/openapi.json", async () => openApiDocument(config.APP_VERSION));
  app.get("/api/v1/locations", { preHandler: withAuth }, async () => store.getLocations());
  app.get("/api/v1/locations/candidates", { preHandler: withAuth }, async (request) => { const query = z.object({ latitude: z.coerce.number().min(-90).max(90), longitude: z.coerce.number().min(-180).max(180), timezone: z.string().optional(), countryCode: z.string().optional() }).parse(request.query); const locations = await store.getLocations(); return locations.map((location) => ({ location, distanceKm: haversineKm(query.latitude, query.longitude, location.latitude, location.longitude), match: matchScore(query, location) })).sort((a, b) => b.match - a.match || a.distanceKm - b.distanceKm).slice(0, 10); });
  app.post("/api/v1/locations", { preHandler: withAuth }, async (request, reply) => reply.code(201).send(await store.createLocation(locationInput.parse(request.body))));
  app.patch("/api/v1/locations/:id", { preHandler: withAuth }, async (request, reply) => { const { id } = idParam.parse(request.params); const parsed = patchLocation.parse(request.body); const { expectedVersion, ...patch } = parsed; try { return await store.updateLocation(id, patch, expectedVersion); } catch (error) { const translated = translateStoreError(error, "LOCATION_UPDATE_FAILED"); return reply.code(translated.error === "SYNC_CONFLICT" ? 409 : translated.error === "LOCATION_NOT_FOUND" ? 404 : 400).send(translated); } });
  app.post("/api/v1/locations/reorder", { preHandler: withAuth }, async (request) => { const { ids } = reorderInput.parse(request.body); const locations = await store.getLocations(); const byId = new Map(locations.map((location) => [location.id, location])); for (const [index, id] of ids.entries()) if (byId.has(id)) await store.updateLocation(id, { sortOrder: index }); return store.getLocations(); });
  app.delete("/api/v1/locations/:id", { preHandler: withAuth }, async (request, reply) => { const { id } = idParam.parse(request.params); try { return await store.deleteLocation(id); } catch (error) { const translated = translateStoreError(error, "LOCATION_DELETE_FAILED"); return reply.code(translated.error === "LOCATION_NOT_FOUND" ? 404 : 400).send(translated); } });
  app.get("/api/v1/locations/sync", { preHandler: withAuth }, async (request) => { const query = syncQuery.parse(request.query); return store.getChanges(query.since, query.limit); });
  app.get("/api/v1/locations/:id/forecast", { preHandler: withAuth }, async (request, reply) => { const { id } = idParam.parse(request.params); const location = await store.getLocation(id); if (!location || location.deletedAt !== null) return reply.code(404).send({ error: "LOCATION_NOT_FOUND" }); const forecast = await store.getForecast(id); if (!forecast) return reply.code(503).send({ error: "FORECAST_NOT_READY", message: "No completed provider run is available yet" }); return forecast; });
  app.get("/api/v1/locations/:id/analysis", { preHandler: withAuth }, async (request, reply) => { const { id } = idParam.parse(request.params); const location = await store.getLocation(id); if (!location || location.deletedAt !== null) return reply.code(404).send({ error: "LOCATION_NOT_FOUND" }); const forecast = await store.getForecast(id); return { locationId: id, generatedAt: forecast?.generatedAt ?? null, contributingModels: forecast?.contributingModels ?? [], confidence: forecast?.hourly.length ? forecast.hourly.reduce((sum, point) => sum + point.confidence, 0) / forecast.hourly.length : 0, methodology: { calibration: (await store.getSettings()).calibrationEnabled ? "enabled-with-sample-gate" : "disabled", wind: "circular-mean", weatherCode: "severity-weighted-mode", spread: "weighted-standard-deviation" }, disagreements: forecast?.hourly.slice(0, 48).map((point) => ({ validAt: point.validAt, spread: point.spread, confidence: point.confidence })) ?? [] }; });
  app.get("/api/v1/locations/:id/evolution", { preHandler: withAuth }, async (request, reply) => { const { id } = idParam.parse(request.params); const location = await store.getLocation(id); if (!location || location.deletedAt !== null) return reply.code(404).send({ error: "LOCATION_NOT_FOUND" }); const query = evolutionQuery.parse(request.query); return { locationId: id, variable: query.variable, values: await store.getEvolution(id, query.variable, query.validAt) }; });
  app.get("/api/v1/locations/:id/performance", { preHandler: withAuth }, async (request, reply) => { const { id } = idParam.parse(request.params); const location = await store.getLocation(id); if (!location || location.deletedAt !== null) return reply.code(404).send({ error: "LOCATION_NOT_FOUND" }); return store.getPerformance(id); });
  app.get("/api/v1/sources", { preHandler: withAuth }, async () => ({ providers: [{ id: "open-meteo", name: "Open-Meteo", status: "configured", apiKeyRequired: false }], models: MODEL_REGISTRY, fetchedAt: new Date().toISOString() }));
  app.get("/api/v1/settings", { preHandler: withAuth }, async () => store.getSettings());
  app.patch("/api/v1/settings", { preHandler: withAuth }, async (request) => store.updateSettings(settingsInput.parse(request.body)));
}

function translateStoreError(error: unknown, fallback: string): { error: string; message?: string } { if (error instanceof Error && error.message === "LOCATION_NOT_FOUND") return { error: "LOCATION_NOT_FOUND" }; if (error instanceof Error && error.message === "SYNC_CONFLICT") return { error: "SYNC_CONFLICT", message: "The location changed since the client last read it" }; return { error: fallback }; }
function haversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number { const rad = Math.PI / 180; const a = Math.sin((lat2 - lat1) * rad / 2) ** 2 + Math.cos(lat1 * rad) * Math.cos(lat2 * rad) * Math.sin((lon2 - lon1) * rad / 2) ** 2; return 6371 * 2 * Math.asin(Math.sqrt(a)); }
function matchScore(query: { latitude: number; longitude: number; timezone?: string | undefined; countryCode?: string | undefined }, location: { latitude: number; longitude: number; timezone: string; countryCode?: string | null }): number { const distance = haversineKm(query.latitude, query.longitude, location.latitude, location.longitude); let score = Math.max(0, 1 - distance / 100); if (query.timezone && query.timezone === location.timezone) score += 0.5; if (query.countryCode && query.countryCode.toUpperCase() === location.countryCode?.toUpperCase()) score += 0.25; return score; }
